name: Equinix Model Training Pipeline

on:
  workflow_dispatch:
    inputs:
      kubeconfig_file:
        description: 'Equinix Kubeconfig File for the Model Training Cluster'
        required: true
        default: 'kubeconfig-9489325180'
      kepler_operator_img:
        description: ''
        required: true
        default: 'quay.io/sustainable_computing_io/kepler-operator:latest'
      kepler_model_server_img:
        description: ''
        required: true
        default: 'quay.io/sustainable_computing_io/kepler_model_server:v0.7'
      

jobs:
  Run-Training:
    name: "Run Training"
    runs-on: ubuntu-latest

    env:
      TEKTON_PATH: '~/kepler-model-server/model-training/tekton'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 

      - name: Make Commands executable
        run: | 
          chmod +x commands/*
      # may not need jq
      - name: Install git and jq
        run: |
          sudo apt-get update
          sudo apt-get install git jq -y

      - name: Install Kubectl
        run: ./commands/install_kubectl_perm.sh # this likely does not exist. need to clone the equnix repo

      - name: Install Tekton 
        run: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

      - name: mkdir ~/.kube
        run: |
          mkdir -p ~/.kube

      - name: Download kubeconfig
        uses: actions/download-artifact@v2
        with:
          # TODO: rename according to run_id 
          name: ${{ github.event.inputs.kubeconfig_file }}
          path: ~/.kube/

      - name: Clone current repo
        run: |
          cd ~
          git clone https://github.com/KaiyiLiu1234/equinix-e2e-ms

      - name: Clone Kepler Operator
        run: |
          cd ~
          git clone ${{ github.event.inputs.kepler_operator_img }}

      - name: Deploy Kepler Operator
        # TODO: use my own manifests
        run: |
          cd ~/kepler-operator
          make deploy OPERATOR_IMG=${{ github.event.inputs.kepler_operator_img }}
          kubectl apply -k config/samples/
      
      - name: Clone Kepler Model Server
        run: |
          cd ~
          git clone ${{ github.event.inputs.kepler_model_server_img }}

      # Deploy Tekton Training Resources
      - name: Deploy Tektok Training Tasks
        run: |
          kubectl apply -f ${TEKTON_PATH}/pvc/hostpath.yaml
          kubectl apply -f ${TEKTON_PATH}/tasks
          kubectl apply -f ${TEKTON_PATH}/tasks/s3
          kubectl apply -f ${TEKTON_PATH}/pipelines

      - name: Run Complete Training
        run: kubectl apply -f ${TEKTON_PATH}/examples/complete-pipelinerun.yaml
      
      - name: Deploy Inspector Pod
        run : |
          kubectl apply -f manifests/inspector-pod.yaml
          kubectl wait --for=condition=complete --timeout=90s pod/inspector-pod
          kubectl cp inspector-pod:/mnt/trained_models.tar.gz ~/trained_models.tar.gz

        # this won't work must utilize current repo

      # Upload Models as artifacts
      - name: Upload models as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: trained_models
          path: ~/trained_models.tar.gz
          retention-days: 30
      

      